<?php

namespace Database\Seeders;

use App\Models\AddOn;
use Illuminate\Database\Seeder;

class AddOnSeeder extends Seeder
{
    public function run(): void
    {
        $addOns = [
            [
                'slug' => 'hot-air-balloon',
                'name' => 'Hot Air Balloon Safari',
                'category' => 'In The Air',
                'filter_category' => ['In The Air', 'Adventure'],
                'price' => '+$550',
                'price_numeric' => 550,
                'price_suffix' => 'per person',
                'duration' => '3–4 hours',
                'location' => 'Central Serengeti (Seronera)',
                'best_season' => 'Year-round (weather dependent)',
                'group_size' => 'Up to 16 per balloon',
                'start_time' => '5:30 AM pre-dawn',
                'tagline' => 'The Serengeti from above, at the moment the world turns gold.',
                'hero_images' => [
                    'https://images.unsplash.com/photo-1535532781581-9296b61fe1c9?w=1400&q=80',
                    'https://images.unsplash.com/photo-1516426122078-c23e76319801?w=1400&q=80',
                    'https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=1400&q=80',
                ],
                'overview_prose' => [
                    "There is a moment, around 300 feet above the Serengeti floor, with the balloon still climbing and the savanna spreading beneath you in every direction, when the scale of this place becomes truly comprehensible. From ground level, the Serengeti is vast but intimate: trees at eye level, animals close, horizons cut by vegetation. From above, you see what a million years of wildlife and grassland actually looks like from the perspective of the eagle.",
                    "The dawn balloon safari begins in darkness. You arrive at the launch site before first light, a thorn bush field in the middle of the Serengeti, nothing visible beyond the glow of the inflation burners and the enormous silhouette of the balloon taking shape against the stars. The briefing is calm and professional. The basket carries up to 16 passengers in compartments. Then you rise. Slowly, silently, impossibly, the earth falls away and the Serengeti reveals itself.",
                    "The sunrise colors the savanna in a sequence that no camera fully captures: deep indigo giving way to rose, then amber, then the blazing gold that photographers call the magic hour. Below you, wildlife is waking. Elephant families move through the grey pre-dawn light. A lion pride stirs on a kopje. The wildebeest herds are already moving. One hour in the air. Then a champagne breakfast set on tables in the bush, linen, glassware, and the Serengeti as your dining room. It is one of the finest mornings available anywhere on Earth.",
                ],
                'pull_quote' => 'The earth falls away and the Serengeti reveals itself.',
                'included' => [
                    'Pre-dawn transfer from your camp to launch site (within 45 minutes)',
                    'Safety briefing with licensed pilot',
                    'Approximately 60 minutes in the air',
                    'Champagne bush breakfast upon landing (linen, glassware, full cooked breakfast)',
                    'Flight certificate from the pilot',
                    'Return transfer to your camp',
                    'Third-party liability insurance',
                ],
                'not_included' => [
                    'Additional alcoholic beverages beyond champagne breakfast',
                    'Private basket upgrade (+$800 for groups of 4–6)',
                    'Gratuity for the balloon crew',
                ],
                'timeline' => [],
                'faqs' => [],
                'practical_info' => [],
                'related_slugs' => ['photography-upgrade', 'private-helicopter', 'private-bush-dinner'],
            ],
            [
                'slug' => 'private-bush-dinner',
                'name' => 'Private Bush Dinner',
                'category' => 'On The Ground',
                'filter_category' => ['On The Ground', 'Romance'],
                'price' => '+$180',
                'price_numeric' => 180,
                'price_suffix' => 'per person (min 2)',
                'duration' => '2.5–3 hours',
                'location' => 'Serengeti, Ngorongoro, Tarangire',
                'best_season' => 'Year-round',
                'group_size' => '2–10 guests',
                'start_time' => 'Sunset (6:00 PM)',
                'tagline' => 'A table set for two, in the middle of the wild.',
                'hero_images' => [
                    'https://images.unsplash.com/photo-1551632436-cbf8dd35adfa?w=1400&q=80',
                    'https://images.unsplash.com/photo-1493246507139-91e8fad9978e?w=1400&q=80',
                    'https://images.unsplash.com/photo-1504006833117-8886a355efbf?w=1400&q=80',
                ],
                'overview_prose' => [
                    "No restaurant on Earth has this view. Your private bush dinner begins with your guide driving you to a pre-selected location, a granite kopje above the plains, the bank of a seasonal river, a baobab clearing in Tarangire, as the sun begins its final descent. The camp team has been here since mid-afternoon, setting a table with proper linen, silverware, and crystal under the open African sky.",
                    "You arrive to find lanterns lit, a fire burning nearby, and a sundowner waiting. The sky performs its nightly transformation, amber to rose to the deep purple of an African dusk, while your private chef prepares a three-course dinner that might begin with avocado and local spice, continue with tenderloin and roasted seasonal vegetables, and finish with a chocolate fondant that has somehow materialized in the middle of the wilderness.",
                    "After dark, the sky opens entirely above you. No light pollution. The Southern Cross, the Milky Way in full resolution, and the distant sound of the bush settling into its nocturnal rhythm. This is not just dinner. It is the evening you will describe for the rest of your life.",
                ],
                'pull_quote' => 'No restaurant on Earth has this view.',
                'included' => [
                    'Private vehicle transfer to and from the dinner location',
                    'Sundowner drinks on arrival (two drinks per person)',
                    'Three-course set dinner prepared by your lodge chef',
                    'Full table setting: linen, silverware, crystal glassware, lanterns, candles',
                    'Maasai security escort throughout',
                    'Return transfer after dinner',
                ],
                'not_included' => [
                    'Additional beverages beyond the two included sundowners',
                    'Specialist wine pairing (+$45pp)',
                    'Gratuity for the dinner team',
                ],
                'timeline' => [],
                'faqs' => [],
                'practical_info' => [],
                'related_slugs' => ['honeymoon-package', 'hot-air-balloon', 'night-game-drive'],
            ],
            [
                'slug' => 'photography-upgrade',
                'name' => 'Photography Safari Upgrade',
                'category' => 'On The Ground',
                'filter_category' => ['On The Ground', 'Adventure'],
                'price' => '+$320',
                'price_numeric' => 320,
                'price_suffix' => 'per day',
                'duration' => 'Full day upgrade',
                'location' => 'All safari destinations',
                'best_season' => 'Year-round',
                'group_size' => '1–4 photographers',
                'start_time' => 'Dawn departure (5:30 AM)',
                'tagline' => 'A safari designed around the light, the lens, and the decisive moment.',
                'hero_images' => [
                    'https://images.unsplash.com/photo-1516426122078-c23e76319801?w=1400&q=80',
                    'https://images.unsplash.com/photo-1549366021-9f761d450615?w=1400&q=80',
                    'https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=1400&q=80',
                ],
                'overview_prose' => [
                    "A standard safari game drive is designed around seeing as much as possible. A photography safari is designed around capturing the extraordinary. The difference is in the patience, staying at a sighting for 90 minutes instead of 15, positioning the vehicle for backlight instead of convenience, and having a guide who understands why you need the animal facing left, not right.",
                    "Your photography upgrade converts your regular game drives into photographer-led sessions. A specialist photography guide (or your regular guide with enhanced photography training) ensures vehicle positioning prioritizes composition, lighting conditions dictate the schedule rather than logistics, and extended time at prime sightings is standard, not exceptional.",
                    "We provide a vehicle with bean bag mounts, a pop-up roof optimized for lens stability, and a dust-proof camera cleaning kit. Golden hour departures are earlier and returns later than standard drives. Your guide understands aperture, shutter speed, and why you're shooting at ISO 6400 in the pre-dawn light. This is not a photography course, it's a safari that respects the discipline of wildlife photography.",
                ],
                'pull_quote' => 'The difference is in the patience, staying at a sighting for 90 minutes instead of 15.',
                'included' => [
                    'Specialist photography guide or enhanced guide briefing',
                    'Vehicle with bean bag lens mounts and pop-up roof',
                    'Extended golden hour game drives (earlier departure, later return)',
                    'Priority positioning at sightings for optimal light and composition',
                    'Dust-proof camera cleaning kit in vehicle',
                    'Daily image review sessions (optional, at camp)',
                ],
                'not_included' => [
                    'Camera equipment rental',
                    'Post-processing or editing services',
                    'Printed photographs',
                ],
                'timeline' => [],
                'faqs' => [],
                'practical_info' => [],
                'related_slugs' => ['hot-air-balloon', 'walking-safari', 'night-game-drive'],
            ],
            [
                'slug' => 'zanzibar-extension',
                'name' => 'Zanzibar Beach Extension',
                'category' => 'On The Ground',
                'filter_category' => ['On The Ground', 'Romance'],
                'price' => '+$450',
                'price_numeric' => 450,
                'price_suffix' => 'per person per night',
                'duration' => '3–5 nights',
                'location' => 'Zanzibar Island',
                'best_season' => 'Jun–Oct, Dec–Feb',
                'group_size' => 'Any size',
                'start_time' => 'Flight from Arusha/Dar',
                'tagline' => 'From the dust of the Serengeti to the turquoise stillness of the Indian Ocean.',
                'hero_images' => [
                    'https://images.unsplash.com/photo-1590523741831-ab7e8b8f9c7f?w=1400&q=80',
                    'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1400&q=80',
                    'https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=1400&q=80',
                ],
                'overview_prose' => [
                    "Tanzania is one of the only destinations on Earth where you can combine world-class wildlife safari and world-class Indian Ocean beaches within a 25-minute flight of each other. The contrast, from the dust and drama of the Serengeti to the turquoise stillness of Nungwi Beach, is one of travel's great transitions.",
                    "Your Zanzibar extension begins the moment you land on the island. We transfer you directly to your chosen beach resort, white sand, warm turquoise water, and a rhythm that is the polar opposite of the bush. Three nights is the minimum recommendation; five nights allows you to explore Stone Town, snorkel Mnemba Atoll, and genuinely decompress.",
                    "We select accommodation based on your preference: Nungwi and Kendwa for the best swimming beaches with no tidal extremes, Paje for world-class kitesurfing, or Matemwe for quiet exclusivity. Every option is vetted, every transfer arranged, and the transition from safari vehicle to beach lounger is seamless.",
                ],
                'pull_quote' => 'One of travel\'s great transitions, from the dust of the Serengeti to the turquoise stillness of the Indian Ocean.',
                'included' => [
                    'Domestic flight Arusha/Dar to Zanzibar',
                    'Airport transfers on Zanzibar',
                    'Beach resort accommodation (half-board or full-board)',
                    'Stone Town guided walking tour (half-day)',
                    'Spice tour option',
                ],
                'not_included' => [
                    'International flights',
                    'Water sports and diving excursions',
                    'Alcoholic beverages (unless all-inclusive)',
                    'Zanzibar visa fee (if applicable)',
                ],
                'timeline' => [],
                'faqs' => [],
                'practical_info' => [],
                'related_slugs' => ['private-bush-dinner', 'honeymoon-package', 'photography-upgrade'],
            ],
            [
                'slug' => 'kilimanjaro-day-hike',
                'name' => 'Kilimanjaro Day Hike',
                'category' => 'Adventure',
                'filter_category' => ['Adventure', 'On The Ground'],
                'price' => '+$280',
                'price_numeric' => 280,
                'price_suffix' => 'per person',
                'duration' => '6–8 hours',
                'location' => 'Kilimanjaro National Park',
                'best_season' => 'Year-round (best Jun–Oct, Dec–Feb)',
                'group_size' => '2–8 hikers',
                'start_time' => '7:00 AM',
                'tagline' => 'Walk the lower slopes of Africa\'s highest peak, no summit commitment required.',
                'hero_images' => [
                    'https://images.unsplash.com/photo-1609198092458-38a293c7ac4b?w=1400&q=80',
                    'https://images.unsplash.com/photo-1621414050945-4f5b78967834?w=1400&q=80',
                ],
                'overview_prose' => [
                    "Not everyone has 9 days for the summit. But everyone deserves to feel the mountain beneath their feet. The Kilimanjaro Day Hike takes you into the rainforest zone of Africa's highest peak, an ecosystem of colobus monkeys, ancient trees draped in moss, and the unmistakable sense of ascending something immense.",
                    "You hike from Marangu Gate (1,860m) to Mandara Hut (2,720m) through dense montane rainforest. The trail is well-maintained and moderate in difficulty.",
                    "At Mandara Hut, you rest, take in the views where the forest thins, and enjoy a packed lunch before descending. It is a profound introduction to Kilimanjaro without the physical and time commitment.",
                ],
                'pull_quote' => 'Everyone deserves to feel the mountain beneath their feet.',
                'included' => [
                    'Return transfer from Moshi/Arusha to Marangu Gate',
                    'Licensed Kilimanjaro guide',
                    'National park entry fees',
                    'Packed lunch and water',
                ],
                'not_included' => [
                    'Hiking boots',
                    'Rain gear',
                    'Gratuity for guide and porter',
                ],
                'timeline' => [],
                'faqs' => [],
                'practical_info' => [],
                'related_slugs' => ['walking-safari', 'photography-upgrade'],
            ],
            [
                'slug' => 'maasai-cultural-village',
                'name' => 'Maasai Cultural Village Experience',
                'category' => 'Culture',
                'filter_category' => ['Culture', 'On The Ground'],
                'price' => '+$95',
                'price_numeric' => 95,
                'price_suffix' => 'per person',
                'duration' => '2–3 hours',
                'location' => 'Ngorongoro Highlands',
                'best_season' => 'Year-round',
                'group_size' => '2–12 guests',
                'start_time' => 'Flexible (morning or afternoon)',
                'tagline' => 'Step inside the world of East Africa\'s most iconic people.',
                'hero_images' => [
                    'https://images.unsplash.com/photo-1523805009345-7448845a9e53?w=1400&q=80',
                ],
                'overview_prose' => [
                    "The Maasai are not a tourist attraction, they are a living civilization. Semi-nomadic pastoralists who have walked this land for centuries alongside the wildlife.",
                    "We work with Maasai communities who manage their own cultural tourism programs and receive direct economic benefit. Entry fees go directly to the community.",
                    "A visit to a Maasai village is not a performance. It is an invitation into someone's home. You'll meet elders, learn about traditional medicine, witness the famous jumping dance, and understand how this ancient culture coexists with modern Tanzania.",
                ],
                'pull_quote' => 'A visit to a Maasai village is not a performance. It is an invitation into someone\'s home.',
                'included' => [
                    'Transfer to and from the village',
                    'Community entry fee',
                    'Guided tour with Maasai elder',
                    'Traditional jumping dance demonstration',
                    'Opportunity to purchase authentic beadwork',
                ],
                'not_included' => [
                    'Photography fees (if applicable)',
                    'Additional donations to the community',
                ],
                'timeline' => [],
                'faqs' => [],
                'practical_info' => [],
                'related_slugs' => ['walking-safari', 'private-bush-dinner'],
            ],
            [
                'slug' => 'night-game-drive',
                'name' => 'Night Game Drive',
                'category' => 'Adventure',
                'filter_category' => ['Adventure', 'On The Ground'],
                'price' => '+$120',
                'price_numeric' => 120,
                'price_suffix' => 'per person',
                'duration' => '2–3 hours',
                'location' => 'Tarangire, Lake Manyara, Selous',
                'best_season' => 'Year-round',
                'group_size' => '2–6 guests',
                'start_time' => '8:00 PM (after dinner)',
                'tagline' => 'The bush transforms after dark. Meet the hunters of the night.',
                'hero_images' => [
                    'https://images.unsplash.com/photo-1534759926787-89fa60ae19c2?w=1400&q=80',
                ],
                'overview_prose' => [
                    "When the sun sets, a completely different Africa awakens. The diurnal animals settle into sleep, and the nocturnal hunters emerge. The night game drive offers a window into this hidden world, where predators rule and the bush reveals its most secretive inhabitants.",
                    "Equipped with powerful spotlights, your guide scans the darkness for the reflective eyes of leopards, hyenas, genets, and bushbabies. The experience is atmospheric, mysterious, and often yields sightings that daytime drives never see.",
                    "This is not just an extension of your game drive. It's a different safari entirely, conducted under the African stars with the sounds of the night as your soundtrack.",
                ],
                'pull_quote' => 'When the sun sets, a completely different Africa awakens.',
                'included' => [
                    'Guided night drive with spotlight',
                    'Specialist night-driving vehicle',
                    'Hot drinks (tea, coffee, hot chocolate)',
                    'Warm blankets',
                ],
                'not_included' => [
                    'Alcoholic beverages',
                    'Gratuity for guide',
                ],
                'timeline' => [],
                'faqs' => [],
                'practical_info' => [],
                'related_slugs' => ['walking-safari', 'private-bush-dinner'],
            ],
            [
                'slug' => 'walking-safari',
                'name' => 'Walking Safari with Armed Ranger',
                'category' => 'Adventure',
                'filter_category' => ['Adventure', 'On The Ground'],
                'price' => '+$150',
                'price_numeric' => 150,
                'price_suffix' => 'per person',
                'duration' => '3–4 hours',
                'location' => 'Ruaha, Selous, Tarangire periphery',
                'best_season' => 'Jun–Oct (dry season)',
                'group_size' => '2–6 walkers',
                'start_time' => '6:30 AM',
                'tagline' => 'On foot, the bush reveals itself completely differently.',
                'hero_images' => [
                    'https://images.unsplash.com/photo-1504006833117-8886a355efbf?w=1400&q=80',
                ],
                'overview_prose' => [
                    "In a vehicle, you observe Africa. On foot, you inhabit it. The walking safari is the most intimate way to experience the wilderness, engaging all your senses in a way that game drives cannot match.",
                    "You walk in single file behind your guide and armed ranger, learning to read animal tracks, identify medicinal plants, and understand the intricate relationships between species. The pace is slow, deliberate, and profoundly immersive.",
                    "This is not a hike. It's a sensory education conducted at the pace of the bush itself, where every footprint, every bird call, and every scent tells a story.",
                ],
                'pull_quote' => 'In a vehicle, you observe Africa. On foot, you inhabit it.',
                'included' => [
                    'Licensed walking safari guide',
                    'Armed TANAPA ranger escort',
                    'Water and trail snacks',
                    'Binoculars for wildlife spotting',
                ],
                'not_included' => [
                    'Hiking boots',
                    'Gratuity for guide and ranger',
                ],
                'timeline' => [],
                'faqs' => [],
                'practical_info' => [],
                'related_slugs' => ['night-game-drive', 'photography-upgrade'],
            ],
            [
                'slug' => 'honeymoon-package',
                'name' => 'Honeymoon & Romance Package',
                'category' => 'Romance',
                'filter_category' => ['Romance', 'On The Ground'],
                'price' => '+$350',
                'price_numeric' => 350,
                'price_suffix' => 'per couple',
                'duration' => 'Throughout safari',
                'location' => 'All destinations',
                'best_season' => 'Year-round',
                'group_size' => 'Couples only',
                'start_time' => 'Integrated into itinerary',
                'tagline' => 'Because the greatest adventure should be shared with the person you love.',
                'hero_images' => [
                    'https://images.unsplash.com/photo-1551632436-cbf8dd35adfa?w=1400&q=80',
                ],
                'overview_prose' => [
                    "A honeymoon safari is integrated with privacy, intimacy, and overwhelming beauty. This package transforms your safari into a romantic journey, with special touches designed for couples celebrating love.",
                    "From champagne on arrival to private dinners under the stars, every element is curated to create moments you'll remember forever. We understand that your honeymoon is not just a vacation—it's the beginning of a lifetime of shared adventures.",
                    "Let us handle the details while you focus on each other and the breathtaking landscapes of Tanzania.",
                ],
                'pull_quote' => 'A honeymoon measured not in thread count but in sunsets.',
                'included' => [
                    'Room upgrade (subject to availability)',
                    'Private bush dinner for two',
                    'Champagne on arrival',
                    'Romantic turndown service with rose petals',
                    'Private vehicle for game drives',
                ],
                'not_included' => [
                    'Spa treatments',
                    'Special photography sessions',
                ],
                'timeline' => [],
                'faqs' => [],
                'practical_info' => [],
                'related_slugs' => ['private-bush-dinner', 'zanzibar-extension'],
            ],
            [
                'slug' => 'private-helicopter',
                'name' => 'Private Helicopter Flight',
                'category' => 'In The Air',
                'filter_category' => ['In The Air', 'Adventure'],
                'price' => '+$2,800',
                'price_numeric' => 2800,
                'price_suffix' => 'per flight (up to 4 pax)',
                'duration' => '1–2 hours',
                'location' => 'Serengeti, Ngorongoro, Kilimanjaro',
                'best_season' => 'Year-round (weather dependent)',
                'group_size' => '1–4 passengers',
                'start_time' => 'Flexible',
                'tagline' => 'See Tanzania from a perspective reserved for eagles.',
                'hero_images' => [
                    'https://images.unsplash.com/photo-1534759926787-89fa60ae19c2?w=1400&q=80',
                ],
                'overview_prose' => [
                    "A helicopter flight over the Serengeti is an experience that belongs in a different category entirely. Where a balloon drifts with the wind, a helicopter commands the sky, offering precision, flexibility, and access to remote areas no other vehicle can reach.",
                    "Fly directly from your lodge to the heart of the migration, hover above Ngorongoro Crater at sunrise, or land on a remote kopje for a private picnic with views that stretch to the horizon. This is ultimate freedom in the African sky.",
                    "The helicopter is not just transportation. It's a photographic platform, an adventure vehicle, and a private viewing gallery all in one.",
                ],
                'pull_quote' => 'Where a balloon drifts with the wind, a helicopter commands the sky.',
                'included' => [
                    'Private helicopter charter',
                    'Licensed commercial pilot',
                    'Custom flight route planning',
                    'All landing fees and permits',
                ],
                'not_included' => [
                    'Gratuity for pilot',
                    'Additional passengers beyond 4',
                ],
                'timeline' => [],
                'faqs' => [],
                'practical_info' => [],
                'related_slugs' => ['hot-air-balloon', 'photography-upgrade'],
            ],
        ];

        foreach ($addOns as $addOn) {
            \App\Models\AddOn::updateOrCreate(['slug' => $addOn['slug']], $addOn);
        }
    }
}
