<?php

namespace Database\Seeders;

use App\Models\AddOn;
use Illuminate\Database\Seeder;

class AddOnSeeder extends Seeder
{
    public function run(): void
    {
        $addOns = [
            [
                'slug' => 'hot-air-balloon',
                'name' => 'Hot Air Balloon Safari',
                'category' => 'In the Air',
                'filter_category' => ['In the Air', 'Adventure'],
                'price' => '+$550',
                'price_numeric' => 550,
                'price_suffix' => 'per person',
                'duration' => '3–4 hours',
                'location' => 'Central Serengeti (Seronera)',
                'best_season' => 'Year-round (weather dependent)',
                'group_size' => 'Up to 16 per balloon',
                'start_time' => '5:30 AM pre-dawn',
                'tagline' => 'The Serengeti from above, at the moment the world turns gold.',
                'hero_images' => [
                    'https://images.unsplash.com/photo-1535532781581-9296b61fe1c9?w=1400&q=80',
                    'https://images.unsplash.com/photo-1516426122078-c23e76319801?w=1400&q=80',
                    'https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=1400&q=80',
                ],
                'overview_prose' => [
                    "There is a moment, around 300 feet above the Serengeti floor, with the balloon still climbing and the savanna spreading beneath you in every direction, when the scale of this place becomes truly comprehensible. From ground level, the Serengeti is vast but intimate: trees at eye level, animals close, horizons cut by vegetation. From above, you see what a million years of wildlife and grassland actually looks like from the perspective of the eagle.",
                    "The dawn balloon safari begins in darkness. You arrive at the launch site before first light, a thorn bush field in the middle of the Serengeti, nothing visible beyond the glow of the inflation burners and the enormous silhouette of the balloon taking shape against the stars. The briefing is calm and professional. The basket carries up to 16 passengers in compartments. Then you rise. Slowly, silently, impossibly, the earth falls away and the Serengeti reveals itself.",
                    "The sunrise colors the savanna in a sequence that no camera fully captures: deep indigo giving way to rose, then amber, then the blazing gold that photographers call the magic hour. Below you, wildlife is waking. Elephant families move through the grey pre-dawn light. A lion pride stirs on a kopje. The wildebeest herds are already moving. One hour in the air. Then a champagne breakfast set on tables in the bush, linen, glassware, and the Serengeti as your dining room. It is one of the finest mornings available anywhere on Earth.",
                ],
                'pull_quote' => 'The earth falls away and the Serengeti reveals itself.',
                'included' => [
                    'Pre-dawn transfer from your camp to launch site (within 45 minutes)',
                    'Safety briefing with licensed pilot',
                    'Approximately 60 minutes in the air',
                    'Champagne bush breakfast upon landing (linen, glassware, full cooked breakfast)',
                    'Flight certificate from the pilot',
                    'Return transfer to your camp',
                    'Third-party liability insurance',
                ],
                'not_included' => [
                    'Additional alcoholic beverages beyond champagne breakfast',
                    'Private basket upgrade (+$800 for groups of 4–6)',
                    'Gratuity for the balloon crew',
                ],
                'timeline' => [
                    ['time' => '05:30 AM', 'title' => 'Pre-dawn Pickup', 'description' => 'Your Ronjoo guide drives you to the launch site in the dark. The anticipation builds as you watch the stars fade.'],
                    ['time' => '05:45 AM', 'title' => 'Arrival & Briefing', 'description' => 'Watch the balloon inflate by floodlight. Briefing from the pilot on safety and what to expect.'],
                    ['time' => '06:00 AM', 'title' => 'Lift Off', 'description' => 'The burners fire, the basket tips upright, and you rise into the sky at first light.'],
                    ['time' => '06:05 AM', 'title' => 'In the Air', 'description' => '60 minutes drifting over the Serengeti. The pilot reads the wind to position you over wildlife and toward the best light.'],
                    ['time' => '07:00 AM', 'title' => 'Landing', 'description' => 'Chase vehicle follows the balloon and marks the landing zone. A gentle touchdown in the savanna.'],
                    ['time' => '07:15 AM', 'title' => 'Champagne Breakfast', 'description' => 'Tables set in the bush. Toast your morning with Champagne and a full cooked breakfast under the African sky.'],
                    ['label' => 'Return Transfer', 'value' => 'Drive back to your lodge under the African night sky.'],
                ],
                'faqs' => [
                    ['question' => 'Is it safe?', 'answer' => 'Commercial balloon operators in Tanzania are licensed and regulated by the Tanzania Civil Aviation Authority. We work exclusively with operators who have maintained perfect safety records for 15+ years.'],
                    ['question' => 'What if the weather is bad?', 'answer' => 'Balloon safaris are weather-dependent. If conditions are unsuitable on your morning (strong winds, storms), the flight is rescheduled to the following day. If rescheduling is not possible due to departure date, a full refund is given.'],
                    ['question' => 'Can children do this?', 'answer' => 'Minimum age is 7 years. Children must be tall enough to see over the basket rim (approximately 120cm).'],
                    ['question' => 'How high do you fly?', 'answer' => 'Altitude varies with wind conditions, typically between 50 and 1,000 feet above ground. The pilot adjusts altitude to optimize wildlife viewing and light conditions.'],
                    ['question' => 'Is photography possible?', 'answer' => 'Absolutely, the balloon offers one of the finest photography platforms in East Africa. Bring your longest lens. Camera straps are essential, no unsecured items in the basket.'],
                ],
                'practical_info' => [
                    ['label' => 'Meeting Point', 'value' => 'Pickup from your Serengeti lodge/camp'],
                    ['label' => 'Departure Time', 'value' => '5:30 AM (pre-dawn)'],
                    ['label' => 'Duration', 'value' => '3–4 hours total'],
                    ['label' => 'What to Wear', 'value' => 'Warm layers, it\'s cold at altitude before dawn. Flat shoes.'],
                    ['label' => 'What to Bring', 'value' => 'Camera with strap, sunglasses, warm jacket'],
                    ['label' => 'Cancellation', 'value' => 'Free cancellation due to weather. 48h notice for voluntary cancellation.'],
                    ['label' => 'Age / Fitness', 'value' => 'Min age 7. Min height 120cm. Moderate fitness, must climb into basket.'],
                ],
                'related_slugs' => ['photography-upgrade', 'private-helicopter', 'private-bush-dinner'],
            ],
            [
                'slug' => 'private-bush-dinner',
                'name' => 'Private Bush Dinner',
                'category' => 'On the Ground',
                'filter_category' => ['On the Ground', 'Romance'],
                'price' => '+$180',
                'price_numeric' => 180,
                'price_suffix' => 'per person (min 2)',
                'duration' => '2.5–3 hours',
                'location' => 'Serengeti, Ngorongoro, Tarangire',
                'best_season' => 'Year-round',
                'group_size' => '2–10 guests',
                'start_time' => 'Sunset (6:00 PM)',
                'tagline' => 'A table set for two, in the middle of the wild.',
                'hero_images' => [
                    'https://images.unsplash.com/photo-1551632436-cbf8dd35adfa?w=1400&q=80',
                    'https://images.unsplash.com/photo-1493246507139-91e8fad9978e?w=1400&q=80',
                    'https://images.unsplash.com/photo-1504006833117-8886a355efbf?w=1400&q=80',
                ],
                'overview_prose' => [
                    "No restaurant on Earth has this view. Your private bush dinner begins with your guide driving you to a pre-selected location, a granite kopje above the plains, the bank of a seasonal river, a baobab clearing in Tarangire, as the sun begins its final descent. The camp team has been here since mid-afternoon, setting a table with proper linen, silverware, and crystal under the open African sky.",
                    "You arrive to find lanterns lit, a fire burning nearby, and a sundowner waiting. The sky performs its nightly transformation, amber to rose to the deep purple of an African dusk, while your private chef prepares a three-course dinner that might begin with avocado and local spice, continue with tenderloin and roasted seasonal vegetables, and finish with a chocolate fondant that has somehow materialized in the middle of the wilderness.",
                    "After dark, the sky opens entirely above you. No light pollution. The Southern Cross, the Milky Way in full resolution, and the distant sound of the bush settling into its nocturnal rhythm. This is not just dinner. It is the evening you will describe for the rest of your life.",
                ],
                'pull_quote' => 'No restaurant on Earth has this view.',
                'included' => [
                    'Private vehicle transfer to and from the dinner location',
                    'Sundowner drinks on arrival (two drinks per person)',
                    'Three-course set dinner prepared by your lodge chef',
                    'Full table setting: linen, silverware, crystal glassware, lanterns, candles',
                    'Maasai security escort throughout',
                    'Return transfer after dinner',
                ],
                'not_included' => [
                    'Additional beverages beyond the two included sundowners',
                    'Specialist wine pairing (+$45pp)',
                    'Gratuity for the dinner team',
                ],
                'timeline' => [
                    ['time' => '17:45', 'title' => 'Vehicle Pickup', 'description' => 'Your guide collects you from your lodge as the afternoon light softens.'],
                    ['time' => '18:00', 'title' => 'Arrival & Sundowners', 'description' => 'Arrive at the dinner location. Sundowner drinks served as you watch the sunset paint the sky.'],
                    ['time' => '18:30', 'title' => 'Sunset Transition', 'description' => 'Lanterns lit. Table dressed. Your starter is served as darkness falls across the savanna.'],
                    ['time' => '19:00', 'title' => 'Dinner Service', 'description' => 'Full three-course dinner under the stars. Total privacy. The Milky Way as your ceiling.'],
                    ['time' => '21:00', 'title' => 'Return Transfer', 'description' => 'Drive back to your lodge under the African night sky.'],
                ],
                'faqs' => [
                    ['question' => 'Can the menu accommodate dietary requirements?', 'answer' => 'Yes, inform us at booking: vegetarian, vegan, gluten-free, halal, allergies. All menus are custom-prepared by the lodge chef.'],
                    ['question' => 'Is it safe in the bush after dark?', 'answer' => 'Yes. A Maasai ranger or armed escort is present throughout the dinner. Your guide is also on-site. The table location is pre-scouted and deemed safe by the lodge team.'],
                    ['question' => 'Can this be combined with a marriage proposal?', 'answer' => 'Absolutely. We arrange surprise proposal setups regularly, rose petals, personalized notes, special menu, photography service. Contact us with your plans and we will design the moment.'],
                    ['question' => 'Can we have a bonfire?', 'answer' => 'A small campfire is standard near all bush dinner setups. Larger bonfires depend on fire risk conditions on the night.'],
                    ['question' => 'What happens if it rains?', 'answer' => 'A covered backup location is always prepared. Rain in the bush is rare during peak season but we are always prepared with a contingency plan.'],
                ],
                'practical_info' => [
                    ['label' => 'Meeting Point', 'value' => 'Pickup from your lodge'],
                    ['label' => 'Departure Time', 'value' => '5:45 PM (sunset)'],
                    ['label' => 'Duration', 'value' => '2.5–3 hours'],
                    ['label' => 'What to Wear', 'value' => 'Smart casual. Warm layer for after dark.'],
                    ['label' => 'What to Bring', 'value' => 'Camera, warm jacket. Everything else is provided.'],
                    ['label' => 'Cancellation', 'value' => '24h notice. Weather cancellations fully refundable.'],
                    ['label' => 'Age / Fitness', 'value' => 'All ages welcome. No fitness requirement.'],
                ],
                'related_slugs' => ['honeymoon-package', 'hot-air-balloon', 'night-game-drive'],
            ],
            [
                'slug' => 'photography-upgrade',
                'name' => 'Photography Safari Upgrade',
                'category' => 'On the Ground',
                'filter_category' => ['On the Ground', 'Adventure'],
                'price' => '+$320',
                'price_numeric' => 320,
                'price_suffix' => 'per day',
                'duration' => 'Full day upgrade',
                'location' => 'All safari destinations',
                'best_season' => 'Year-round',
                'group_size' => '1–4 photographers',
                'start_time' => 'Dawn departure (5:30 AM)',
                'tagline' => 'A safari designed around the light, the lens, and the decisive moment.',
                'hero_images' => [
                    'https://images.unsplash.com/photo-1516426122078-c23e76319801?w=1400&q=80',
                    'https://images.unsplash.com/photo-1549366021-9f761d450615?w=1400&q=80',
                    'https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=1400&q=80',
                ],
                'overview_prose' => [
                    "A standard safari game drive is designed around seeing as much as possible. A photography safari is designed around capturing the extraordinary. The difference is in the patience, staying at a sighting for 90 minutes instead of 15, positioning the vehicle for backlight instead of convenience, and having a guide who understands why you need the animal facing left, not right.",
                    "Your photography upgrade converts your regular game drives into photographer-led sessions. A specialist photography guide (or your regular guide with enhanced photography training) ensures vehicle positioning prioritizes composition, lighting conditions dictate the schedule rather than logistics, and extended time at prime sightings is standard, not exceptional.",
                    "We provide a vehicle with bean bag mounts, a pop-up roof optimized for lens stability, and a dust-proof camera cleaning kit. Golden hour departures are earlier and returns later than standard drives. Your guide understands aperture, shutter speed, and why you're shooting at ISO 6400 in the pre-dawn light. This is not a photography course, it's a safari that respects the discipline of wildlife photography.",
                ],
                'pull_quote' => 'The difference is in the patience, staying at a sighting for 90 minutes instead of 15.',
                'included' => [
                    'Specialist photography guide or enhanced guide briefing',
                    'Vehicle with bean bag lens mounts and pop-up roof',
                    'Extended golden hour game drives (earlier departure, later return)',
                    'Priority positioning at sightings for optimal light and composition',
                    'Dust-proof camera cleaning kit in vehicle',
                    'Daily image review sessions (optional, at camp)',
                ],
                'not_included' => [
                    'Camera equipment rental',
                    'Post-processing or editing services',
                    'Printed photographs',
                ],
                'faqs' => [
                    ['question' => 'Do I need professional equipment?', 'answer' => 'No. The upgrade benefits any camera, including smartphones. However, a DSLR or mirrorless camera with a 200mm+ telephoto lens will maximize the experience.'],
                    ['question' => 'Can beginners benefit from this?', 'answer' => 'Absolutely. The photography guide adjusts to your skill level. Beginners receive practical tips during drives; experienced photographers get positioning and timing support.'],
                    ['question' => 'How many photographers per vehicle?', 'answer' => 'Maximum 4 to ensure everyone has shooting space and window access. For serious photographers, we recommend 2 per vehicle.'],
                    ['question' => 'Is there post-processing help available?', 'answer' => 'Yes, at an additional fee, we can arrange evening editing workshops with the photography guide at camp.'],
                    ['question' => 'Which parks are best for photography?', 'answer' => 'The Serengeti for big cats and migration. Ngorongoro for concentrated wildlife density. Tarangire for elephants and dramatic baobab landscapes. Each park offers unique photographic opportunities.'],
                ],
                'practical_info' => [
                    ['label' => 'Meeting Point', 'value' => 'Your safari vehicle, upgrade applied to existing drives'],
                    ['label' => 'Departure Time', 'value' => '5:30 AM (earlier than standard)'],
                    ['label' => 'Duration', 'value' => 'Full day game drives'],
                    ['label' => 'What to Wear', 'value' => 'Neutral earth tones. No bright colors.'],
                    ['label' => 'What to Bring', 'value' => 'Camera, extra batteries, memory cards, lens cleaning cloth'],
                    ['label' => 'Cancellation', 'value' => '48h notice for full refund'],
                    ['label' => 'Age / Fitness', 'value' => 'All ages. Standard safari fitness.'],
                ],
                'related_slugs' => ['hot-air-balloon', 'walking-safari', 'night-game-drive'],
            ],
            [
                'slug' => 'zanzibar-extension',
                'name' => 'Zanzibar Beach Extension',
                'category' => 'On the Ground',
                'filter_category' => ['On the Ground', 'Romance'],
                'price' => '+$450',
                'price_numeric' => 450,
                'price_suffix' => 'per person per night',
                'duration' => '3–5 nights',
                'location' => 'Zanzibar Island',
                'best_season' => 'Jun–Oct, Dec–Feb',
                'group_size' => 'Any size',
                'start_time' => 'Flight from Arusha/Dar',
                'tagline' => 'From the dust of the Serengeti to the turquoise stillness of the Indian Ocean.',
                'hero_images' => [
                    'https://images.unsplash.com/photo-1590523741831-ab7e8b8f9c7f?w=1400&q=80',
                    'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1400&q=80',
                    'https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=1400&q=80',
                ],
                'overview_prose' => [
                    "Tanzania is one of the only destinations on Earth where you can combine world-class wildlife safari and world-class Indian Ocean beaches within a 25-minute flight of each other. The contrast, from the dust and drama of the Serengeti to the turquoise stillness of Nungwi Beach, is one of travel's great transitions.",
                    "Your Zanzibar extension begins the moment you land on the island. We transfer you directly to your chosen beach resort, white sand, warm turquoise water, and a rhythm that is the polar opposite of the bush. Three nights is the minimum recommendation; five nights allows you to explore Stone Town, snorkel Mnemba Atoll, and genuinely decompress.",
                    "We select accommodation based on your preference: Nungwi and Kendwa for the best swimming beaches with no tidal extremes, Paje for world-class kitesurfing, or Matemwe for quiet exclusivity. Every option is vetted, every transfer arranged, and the transition from safari vehicle to beach lounger is seamless.",
                ],
                'pull_quote' => 'One of travel\'s great transitions, from the dust of the Serengeti to the turquoise stillness of the Indian Ocean.',
                'included' => [
                    'Domestic flight Arusha/Dar to Zanzibar',
                    'Airport transfers on Zanzibar',
                    'Beach resort accommodation (half-board or full-board)',
                    'Stone Town guided walking tour (half-day)',
                    'Spice tour option',
                ],
                'not_included' => [
                    'International flights',
                    'Water sports and diving excursions',
                    'Alcoholic beverages (unless all-inclusive)',
                    'Zanzibar visa fee (if applicable)',
                ],
                'faqs' => [
                    ['question' => 'How do we get to Zanzibar from the safari?', 'answer' => 'A 25–45 minute domestic flight from Arusha or Dar es Salaam. We arrange everything, you simply walk from the safari vehicle to the airport.'],
                    ['question' => 'Which beach area do you recommend?', 'answer' => 'Nungwi or Kendwa for swimming at all tides. Paje for kitesurfing. Matemwe for quiet seclusion. We recommend based on your preferences.'],
                    ['question' => 'Is 3 nights enough?', 'answer' => '3 nights is the minimum for genuine relaxation. 5 nights allows for exploration of Stone Town, snorkeling, and deeper unwinding.'],
                    ['question' => 'Can we add diving or snorkeling?', 'answer' => 'Yes, Mnemba Atoll snorkeling trips and PADI dive courses can be arranged through your resort. We recommend booking in advance for peak season.'],
                    ['question' => 'Do we need to dress modestly?', 'answer' => 'At resorts, beach attire is fine. In Stone Town and villages, covered shoulders and knees are required and respectful. Zanzibar is predominantly Muslim.'],
                ],
                'practical_info' => [
                    ['label' => 'Meeting Point', 'value' => 'Arusha/Dar es Salaam airport'],
                    ['label' => 'Departure Time', 'value' => 'Morning flight (varies)'],
                    ['label' => 'Duration', 'value' => '3–5 nights recommended'],
                    ['label' => 'What to Wear', 'value' => 'Light, breathable clothing. Modest dress for Stone Town.'],
                    ['label' => 'What to Bring', 'value' => 'Sunscreen, swimwear, reef-safe sun protection'],
                    ['label' => 'Cancellation', 'value' => 'Subject to flight and hotel cancellation policies'],
                    ['label' => 'Age / Fitness', 'value' => 'All ages and fitness levels'],
                ],
                'related_slugs' => ['private-bush-dinner', 'honeymoon-package', 'photography-upgrade'],
            ],
            [
                'slug' => 'kilimanjaro-day-hike',
                'name' => 'Kilimanjaro Day Hike',
                'category' => 'Adventure',
                'filter_category' => ['Adventure', 'On the Ground'],
                'price' => '+$280',
                'price_numeric' => 280,
                'price_suffix' => 'per person',
                'duration' => '6–8 hours',
                'location' => 'Kilimanjaro National Park',
                'best_season' => 'Year-round (best Jun–Oct, Dec–Feb)',
                'group_size' => '2–8 hikers',
                'start_time' => '7:00 AM',
                'tagline' => 'Walk the lower slopes of Africa\'s highest peak, no summit commitment required.',
                'hero_images' => [
                    'https://images.unsplash.com/photo-1609198092458-38a293c7ac4b?w=1400&q=80',
                    'https://images.unsplash.com/photo-1621414050945-4f5b78967834?w=1400&q=80',
                ],
                'overview_prose' => [
                    "Not everyone has 9 days for the summit. But everyone deserves to feel the mountain beneath their feet. The Kilimanjaro Day Hike takes you into the rainforest zone of Africa's highest peak, an ecosystem of colobus monkeys, ancient trees draped in moss, and the unmistakable sense of ascending something immense.",
                    "You hike from Marangu Gate (1,860m) to Mandara Hut (2,720m) through dense montane rainforest. The trail is well-maintained and moderate in difficulty.",
                    "At Mandara Hut, you rest, take in the views where the forest thins, and enjoy a packed lunch before descending. It is a profound introduction to Kilimanjaro without the physical and time commitment.",
                ],
                'pull_quote' => 'Everyone deserves to feel the mountain beneath their feet.',
                'included' => [
                    'Return transfer from Moshi/Arusha to Marangu Gate',
                    'Licensed Kilimanjaro guide',
                    'National park entry fees',
                    'Packed lunch and water',
                ],
                'not_included' => [
                    'Hiking boots',
                    'Rain gear',
                    'Gratuity for guide and porter',
                ],
                'faqs' => [
                    ['question' => 'How fit do I need to be?', 'answer' => 'Moderate fitness is sufficient. If you can walk for 4–5 hours at a steady pace with some incline, you will manage comfortably.'],
                    ['question' => 'Is this suitable for children?', 'answer' => 'Yes, minimum age is 6.'],
                ],
                'practical_info' => [
                    ['label' => 'Meeting Point', 'value' => 'Hotel pickup in Moshi or Arusha'],
                    ['label' => 'Departure Time', 'value' => '7:00 AM'],
                    ['label' => 'Duration', 'value' => '6–8 hours (incl. transfers)'],
                ],
                'related_slugs' => ['walking-safari', 'photography-upgrade'],
            ],
            [
                'slug' => 'maasai-cultural-village',
                'name' => 'Maasai Cultural Village Experience',
                'category' => 'Culture',
                'filter_category' => ['Culture', 'On the Ground'],
                'price' => '+$95',
                'price_numeric' => 95,
                'price_suffix' => 'per person',
                'duration' => '2–3 hours',
                'location' => 'Ngorongoro Highlands',
                'best_season' => 'Year-round',
                'group_size' => '2–12 guests',
                'start_time' => 'Flexible (morning or afternoon)',
                'tagline' => 'Step inside the world of East Africa\'s most iconic people.',
                'hero_images' => [
                    'https://images.unsplash.com/photo-1523805009345-7448845a9e53?w=1400&q=80',
                ],
                'overview_prose' => [
                    "The Maasai are not a tourist attraction, they are a living civilization. Semi-nomadic pastoralists who have walked this land for centuries alongside the wildlife.",
                    "We work with Maasai communities who manage their own cultural tourism programs and receive direct economic benefit. Entry fees go directly to the community.",
                ],
                'pull_quote' => 'A visit to a Maasai village is not a performance. It is an invitation into someone\'s home.',
                'included' => [
                    'Transfer to and from the village',
                    'Community entry fee',
                    'Guided tour with Maasai elder',
                ],
                'not_included' => [
                    'Beadwork purchases',
                    'Photography fees (if applicable)',
                ],
                'faqs' => [
                    ['question' => 'Is this an authentic visit?', 'answer' => 'Yes. We only work with communities who manage their own tourism programs.'],
                ],
                'practical_info' => [
                    ['label' => 'Duration', 'value' => '2–3 hours'],
                    ['label' => 'What to Wear', 'value' => 'Respectful, modest clothing.'],
                ],
                'related_slugs' => ['walking-safari', 'private-bush-dinner'],
            ],
            [
                'slug' => 'night-game-drive',
                'name' => 'Night Game Drive',
                'category' => 'Adventure',
                'filter_category' => ['Adventure', 'On the Ground'],
                'price' => '+$120',
                'price_numeric' => 120,
                'price_suffix' => 'per person',
                'duration' => '2–3 hours',
                'location' => 'Tarangire, Lake Manyara, Selous',
                'best_season' => 'Year-round',
                'group_size' => '2–6 guests',
                'start_time' => '8:00 PM (after dinner)',
                'tagline' => 'The bush transforms after dark. Meet the hunters of the night.',
                'hero_images' => [
                    'https://images.unsplash.com/photo-1534759926787-89fa60ae19c2?w=1400&q=80',
                ],
                'overview_prose' => [
                    "When the sun sets, a completely different Africa awakens. The diurnal animals settle into sleep, and the nocturnal hunters emerge.",
                ],
                'pull_quote' => 'When the sun sets, a completely different Africa awakens.',
                'included' => [
                    'Guided night drive with spotlight',
                    'Specialist night-driving vehicle',
                    'Hot drinks (tea, coffee, hot chocolate)',
                ],
                'not_included' => [
                    'Alcoholic beverages',
                    'Gratuity',
                ],
                'faqs' => [
                    ['question' => 'Which parks offer night drives?', 'answer' => 'Tarangire, Lake Manyara, and Selous/Nyerere.'],
                ],
                'practical_info' => [
                    ['label' => 'Departure Time', 'value' => '8:00 PM (after dinner)'],
                    ['label' => 'Duration', 'value' => '2–3 hours'],
                    ['label' => 'What to Wear', 'value' => 'Very warm layers.'],
                ],
                'related_slugs' => ['walking-safari', 'private-bush-dinner'],
            ],
            [
                'slug' => 'walking-safari',
                'name' => 'Walking Safari with Armed Ranger',
                'category' => 'Adventure',
                'filter_category' => ['Adventure', 'On the Ground'],
                'price' => '+$150',
                'price_numeric' => 150,
                'price_suffix' => 'per person',
                'duration' => '3–4 hours',
                'location' => 'Ruaha, Selous, Tarangire periphery',
                'best_season' => 'Jun–Oct (dry season)',
                'group_size' => '2–6 walkers',
                'start_time' => '6:30 AM',
                'tagline' => 'On foot, the bush reveals itself completely differently.',
                'hero_images' => [
                    'https://images.unsplash.com/photo-1504006833117-8886a355efbf?w=1400&q=80',
                ],
                'overview_prose' => [
                    "In a vehicle, you observe Africa. On foot, you inhabit it.",
                ],
                'pull_quote' => 'In a vehicle, you observe Africa. On foot, you inhabit it.',
                'included' => [
                    'Licensed walking safari guide',
                    'Armed TANAPA ranger escort',
                    'Water and trail snacks',
                ],
                'not_included' => [
                    'Hiking boots',
                    'Gratuity',
                ],
                'faqs' => [
                    ['question' => 'Is it dangerous?', 'answer' => 'Conducted by highly trained guides with armed ranger escorts.'],
                ],
                'practical_info' => [
                    ['label' => 'Departure Time', 'value' => '6:30 AM'],
                    ['label' => 'Duration', 'value' => '3–4 hours'],
                ],
                'related_slugs' => ['night-game-drive', 'photography-upgrade'],
            ],
            [
                'slug' => 'honeymoon-package',
                'name' => 'Honeymoon & Romance Package',
                'category' => 'Romance',
                'filter_category' => ['Romance', 'On the Ground'],
                'price' => '+$350',
                'price_numeric' => 350,
                'price_suffix' => 'per couple',
                'duration' => 'Throughout safari',
                'location' => 'All destinations',
                'best_season' => 'Year-round',
                'group_size' => 'Couples only',
                'start_time' => 'Integrated into itinerary',
                'tagline' => 'Because the greatest adventure should be shared with the person you love.',
                'hero_images' => [
                    'https://images.unsplash.com/photo-1551632436-cbf8dd35adfa?w=1400&q=80',
                ],
                'overview_prose' => [
                    "A honeymoon safari is integrated with privacy, intimacy, and overwhelming beauty.",
                ],
                'pull_quote' => 'A honeymoon measured not in thread count but in sunsets.',
                'included' => [
                    'Room upgrade',
                    'Private bush dinner',
                    'Champagne on arrival',
                ],
                'not_included' => [
                    'Spa treatments',
                ],
                'faqs' => [
                    ['question' => 'Which safari is best for honeymooners?', 'answer' => 'Our Safari & Zanzibar combination is the most popular.'],
                ],
                'practical_info' => [
                    ['label' => 'Duration', 'value' => 'Throughout your safari'],
                ],
                'related_slugs' => ['private-bush-dinner', 'zanzibar-extension'],
            ],
            [
                'slug' => 'private-helicopter',
                'name' => 'Private Helicopter Flight',
                'category' => 'In the Air',
                'filter_category' => ['In the Air', 'Adventure'],
                'price' => '+$2,800',
                'price_numeric' => 2800,
                'price_suffix' => 'per flight (up to 4 pax)',
                'duration' => '1–2 hours',
                'location' => 'Serengeti, Ngorongoro, Kilimanjaro',
                'best_season' => 'Year-round (weather dependent)',
                'group_size' => '1–4 passengers',
                'start_time' => 'Flexible',
                'tagline' => 'See Tanzania from a perspective reserved for eagles.',
                'hero_images' => [
                    'https://images.unsplash.com/photo-1534759926787-89fa60ae19c2?w=1400&q=80',
                ],
                'overview_prose' => [
                    "A helicopter flight over the Serengeti is an experience that belongs in a different category entirely.",
                ],
                'pull_quote' => 'Where a balloon drifts with the wind, a helicopter commands the sky.',
                'included' => [
                    'Private helicopter charter',
                    'Licensed commercial pilot',
                ],
                'not_included' => [
                    'Gratuity for pilot',
                ],
                'faqs' => [
                    ['question' => 'How much does it cost?', 'answer' => '$2,800 covers the entire flight for up to 4 passengers.'],
                ],
                'practical_info' => [
                    ['label' => 'Duration', 'value' => '1–2 hours'],
                ],
                'related_slugs' => ['hot-air-balloon', 'photography-upgrade'],
            ],
        ];

        foreach ($addOns as $addOn) {
            \App\Models\AddOn::updateOrCreate(['slug' => $addOn['slug']], $addOn);
        }
    }
}

