<?php

namespace Database\Seeders;

use App\Models\Enquiry;
use Illuminate\Database\Seeder;

class EnquirySeeder extends Seeder
{
    public function run(): void
    {
        $enquiries = [
            ['guest_name' => 'Alexandra Chen', 'email' => 'alex.chen@example.com', 'whatsapp' => '+1 415 555 0199', 'country' => 'United States', 'country_flag' => '🇺🇸', 'safari_interest' => 'Great Migration Safari', 'preferred_dates' => 'August 2026', 'travelers' => '2', 'budget' => '$5,000-7,000', 'message' => 'Hi, my husband and I are planning our first trip to Africa and the Great Migration is our dream. We want to see the river crossings if possible. Can you help us plan the perfect itinerary?', 'status' => 'new', 'is_read' => false, 'received_at' => '2026-03-09 08:30:00', 'source' => 'Website Form', 'replies' => [], 'tags' => ['High Value']],
            ['guest_name' => 'James Morrison', 'email' => 'james.m@example.com', 'whatsapp' => '+44 7911 123456', 'country' => 'United Kingdom', 'country_flag' => '🇬🇧', 'safari_interest' => 'Kilimanjaro Lemosho Route', 'preferred_dates' => 'September 2026', 'travelers' => '4', 'budget' => '$3,000-4,000 pp', 'message' => 'Looking to climb Kili with 3 mates for my 40th birthday. We are all reasonably fit. Is September a good time?', 'status' => 'in-progress', 'is_read' => true, 'received_at' => '2026-03-08 14:15:00', 'source' => 'WhatsApp', 'replies' => [['from' => 'admin', 'message' => 'Hi James! September is an excellent month for Kilimanjaro. Our 9-day Lemosho success rate is 87%. Let me put together a group quote for 4.', 'timestamp' => '2026-03-08T16:00:00']], 'tags' => ['Group']],
            ['guest_name' => 'Sophie Leclerc', 'email' => 'sophie@example.com', 'whatsapp' => '+33 6 98 76 54 32', 'country' => 'France', 'country_flag' => '🇫🇷', 'safari_interest' => 'Honeymoon Safari & Zanzibar', 'preferred_dates' => 'November 2026', 'travelers' => '2', 'budget' => '$8,000-12,000', 'message' => 'Nous planifions notre lune de miel et adorerions combiner un safari avec la plage. Zanzibar semble parfait.', 'status' => 'new', 'is_read' => false, 'received_at' => '2026-03-09 06:45:00', 'source' => 'Website Form', 'replies' => [], 'tags' => ['Honeymoon', 'High Value']],
            ['guest_name' => 'David & Anne Thompson', 'email' => 'thompson@example.com', 'whatsapp' => '+61 412 345 678', 'country' => 'Australia', 'country_flag' => '🇦🇺', 'safari_interest' => 'Family Safari Adventure', 'preferred_dates' => 'December 2026', 'travelers' => '4', 'budget' => '$10,000-15,000', 'message' => 'We have two children (ages 10 and 14) and want to give them an unforgettable Christmas holiday in Tanzania.', 'status' => 'awaiting-guest', 'is_read' => true, 'received_at' => '2026-03-05 10:00:00', 'source' => 'Website Form', 'replies' => [['from' => 'admin', 'message' => 'Absolutely! We specialize in family safaris. I have put together a custom itinerary with family-friendly lodges.', 'timestamp' => '2026-03-05T14:30:00'], ['from' => 'guest', 'message' => 'This looks wonderful! Can we add a day at Ngorongoro? Also, do any lodges have swimming pools?', 'timestamp' => '2026-03-06T08:15:00'], ['from' => 'admin', 'message' => 'Yes! I have added an extra day at Ngorongoro and selected lodges with pools. Updated itinerary attached.', 'timestamp' => '2026-03-06T11:00:00']], 'tags' => ['Family', 'High Value']],
            ['guest_name' => 'Roberto Esposito', 'email' => 'roberto@example.com', 'whatsapp' => '+39 333 123 4567', 'country' => 'Italy', 'country_flag' => '🇮🇹', 'safari_interest' => 'Photography Safari', 'preferred_dates' => 'July 2026', 'travelers' => '1', 'budget' => '$4,000-5,000', 'message' => 'I am a semi-professional wildlife photographer. Do you have specialized photography safaris?', 'status' => 'in-progress', 'is_read' => true, 'received_at' => '2026-03-07 09:30:00', 'source' => 'Instagram DM', 'replies' => [['from' => 'admin', 'message' => 'We do! Our Photography Safari includes a pop-top vehicle with beanbag mounts, and our guides understand photography timing.', 'timestamp' => '2026-03-07T12:00:00']], 'tags' => ['Photography']],
            ['guest_name' => 'Yuki Tanaka', 'email' => 'yuki@example.com', 'whatsapp' => '+81 80 1234 5678', 'country' => 'Japan', 'country_flag' => '🇯🇵', 'safari_interest' => 'Northern Circuit Classic', 'preferred_dates' => 'January 2027', 'travelers' => '2', 'budget' => '$6,000-8,000', 'message' => 'We are interested in the calving season. Is January the right time?', 'status' => 'new', 'is_read' => false, 'received_at' => '2026-03-09 02:15:00', 'source' => 'Website Form', 'replies' => [], 'tags' => []],
            ['guest_name' => 'Michael & Lisa Anderson', 'email' => 'anderson@example.com', 'whatsapp' => '+1 604 555 0123', 'country' => 'Canada', 'country_flag' => '🇨🇦', 'safari_interest' => 'Kilimanjaro + Safari Combo', 'preferred_dates' => 'October 2026', 'travelers' => '2', 'budget' => '$12,000-15,000', 'message' => 'We want to do Kilimanjaro followed by a safari. What is the best combo package?', 'status' => 'converted', 'is_read' => true, 'received_at' => '2026-02-20 15:00:00', 'source' => 'Website Form', 'replies' => [['from' => 'admin', 'message' => 'The ultimate combo! 9 days Lemosho + 7 days Northern Circuit. I have created a custom package for you.', 'timestamp' => '2026-02-20T18:00:00']], 'tags' => ['High Value', 'Converted']],
            ['guest_name' => 'Anna Johansson', 'email' => 'anna.j@example.com', 'whatsapp' => '+46 70 123 45 67', 'country' => 'Sweden', 'country_flag' => '🇸🇪', 'safari_interest' => 'Southern Circuit Safari', 'preferred_dates' => 'June 2026', 'travelers' => '1', 'budget' => '$5,000-7,000', 'message' => 'I have already done the Northern Circuit. I want to explore Ruaha and Selous this time.', 'status' => 'in-progress', 'is_read' => true, 'received_at' => '2026-03-04 11:00:00', 'source' => 'Email', 'replies' => [['from' => 'admin', 'message' => 'Wonderful choice! The Southern Circuit offers incredible walking safari experiences.', 'timestamp' => '2026-03-04T14:30:00']], 'tags' => ['Return Visitor']],
        ];

        foreach ($enquiries as $enquiry) {
            Enquiry::updateOrCreate(
                ['email' => $enquiry['email'], 'safari_interest' => $enquiry['safari_interest']],
                $enquiry
            );
        }
    }
}
